<?php

/**
 * this file is generated by https://github.com/nisnaker/ide-helper-generator
 *
 *
 * ext info:
 *
 * swoole
 * 
 * swoole support => enabled
 * Version => 2.0.12
 * Author => tianfeng.han[email: mikan.tenny@gmail.com]
 * epoll => enabled
 * eventfd => enabled
 * timerfd => enabled
 * signalfd => enabled
 * spinlock => enabled
 * rwlock => enabled
 * async http/websocket client => enabled
 * Linux Native AIO => enabled
 * pcre => enabled
 * mutex_timedlock => enabled
 * pthread_barrier => enabled
 * futex => enabled
 * 
 * Directive => Local Value => Master Value
 * swoole.aio_thread_num => 2 => 2
 * swoole.display_errors => On => On
 * swoole.use_namespace => On => On
 * swoole.fast_serialize => Off => Off
 * swoole.unixsock_buffer_size => 8388608 => 8388608
 * 
 */


/**
 * ext constants:
 */

defined('SWOOLE_BASE') or define('SWOOLE_BASE', 4);
defined('SWOOLE_THREAD') or define('SWOOLE_THREAD', 2);
defined('SWOOLE_PROCESS') or define('SWOOLE_PROCESS', 3);
defined('SWOOLE_IPC_UNSOCK') or define('SWOOLE_IPC_UNSOCK', 1);
defined('SWOOLE_IPC_MSGQUEUE') or define('SWOOLE_IPC_MSGQUEUE', 2);
defined('SWOOLE_IPC_PREEMPTIVE') or define('SWOOLE_IPC_PREEMPTIVE', 3);
defined('SWOOLE_SOCK_TCP') or define('SWOOLE_SOCK_TCP', 1);
defined('SWOOLE_SOCK_TCP6') or define('SWOOLE_SOCK_TCP6', 3);
defined('SWOOLE_SOCK_UDP') or define('SWOOLE_SOCK_UDP', 2);
defined('SWOOLE_SOCK_UDP6') or define('SWOOLE_SOCK_UDP6', 4);
defined('SWOOLE_SOCK_UNIX_DGRAM') or define('SWOOLE_SOCK_UNIX_DGRAM', 5);
defined('SWOOLE_SOCK_UNIX_STREAM') or define('SWOOLE_SOCK_UNIX_STREAM', 6);
defined('SWOOLE_TCP') or define('SWOOLE_TCP', 1);
defined('SWOOLE_TCP6') or define('SWOOLE_TCP6', 3);
defined('SWOOLE_UDP') or define('SWOOLE_UDP', 2);
defined('SWOOLE_UDP6') or define('SWOOLE_UDP6', 4);
defined('SWOOLE_UNIX_DGRAM') or define('SWOOLE_UNIX_DGRAM', 5);
defined('SWOOLE_UNIX_STREAM') or define('SWOOLE_UNIX_STREAM', 6);
defined('SWOOLE_SOCK_SYNC') or define('SWOOLE_SOCK_SYNC', 0);
defined('SWOOLE_SOCK_ASYNC') or define('SWOOLE_SOCK_ASYNC', 1);
defined('SWOOLE_SYNC') or define('SWOOLE_SYNC', 2048);
defined('SWOOLE_ASYNC') or define('SWOOLE_ASYNC', 1024);
defined('SWOOLE_KEEP') or define('SWOOLE_KEEP', 4096);
defined('SWOOLE_EVENT_READ') or define('SWOOLE_EVENT_READ', 512);
defined('SWOOLE_EVENT_WRITE') or define('SWOOLE_EVENT_WRITE', 1024);
defined('SWOOLE_VERSION') or define('SWOOLE_VERSION', '2.0.12');
defined('SWOOLE_AIO_BASE') or define('SWOOLE_AIO_BASE', 0);
defined('SWOOLE_AIO_LINUX') or define('SWOOLE_AIO_LINUX', 1);
defined('SIGHUP') or define('SIGHUP', 1);
defined('SIGINT') or define('SIGINT', 2);
defined('SIGQUIT') or define('SIGQUIT', 3);
defined('SIGILL') or define('SIGILL', 4);
defined('SIGTRAP') or define('SIGTRAP', 5);
defined('SIGABRT') or define('SIGABRT', 6);
defined('SIGBUS') or define('SIGBUS', 7);
defined('SIGFPE') or define('SIGFPE', 8);
defined('SIGKILL') or define('SIGKILL', 9);
defined('SIGUSR1') or define('SIGUSR1', 10);
defined('SIGSEGV') or define('SIGSEGV', 11);
defined('SIGUSR2') or define('SIGUSR2', 12);
defined('SIGPIPE') or define('SIGPIPE', 13);
defined('SIGALRM') or define('SIGALRM', 14);
defined('SIGTERM') or define('SIGTERM', 15);
defined('SIGSTKFLT') or define('SIGSTKFLT', 16);
defined('SIGCHLD') or define('SIGCHLD', 17);
defined('SIGCONT') or define('SIGCONT', 18);
defined('SIGSTOP') or define('SIGSTOP', 19);
defined('SIGTSTP') or define('SIGTSTP', 20);
defined('SIGTTIN') or define('SIGTTIN', 21);
defined('SIGTTOU') or define('SIGTTOU', 22);
defined('SIGURG') or define('SIGURG', 23);
defined('SIGXCPU') or define('SIGXCPU', 24);
defined('SIGXFSZ') or define('SIGXFSZ', 25);
defined('SIGVTALRM') or define('SIGVTALRM', 26);
defined('SIGPROF') or define('SIGPROF', 27);
defined('SIGWINCH') or define('SIGWINCH', 28);
defined('SIGIO') or define('SIGIO', 29);
defined('SIGPWR') or define('SIGPWR', 30);
defined('SIGSYS') or define('SIGSYS', 31);
defined('SIG_IGN') or define('SIG_IGN', 1);
defined('SWOOLE_FILELOCK') or define('SWOOLE_FILELOCK', 2);
defined('SWOOLE_MUTEX') or define('SWOOLE_MUTEX', 3);
defined('SWOOLE_SEM') or define('SWOOLE_SEM', 4);
defined('SWOOLE_RWLOCK') or define('SWOOLE_RWLOCK', 1);
defined('SWOOLE_SPINLOCK') or define('SWOOLE_SPINLOCK', 5);
defined('WEBSOCKET_OPCODE_TEXT') or define('WEBSOCKET_OPCODE_TEXT', 1);
defined('WEBSOCKET_OPCODE_BINARY') or define('WEBSOCKET_OPCODE_BINARY', 2);
defined('WEBSOCKET_OPCODE_PING') or define('WEBSOCKET_OPCODE_PING', 9);
defined('WEBSOCKET_STATUS_CONNECTION') or define('WEBSOCKET_STATUS_CONNECTION', 1);
defined('WEBSOCKET_STATUS_HANDSHAKE') or define('WEBSOCKET_STATUS_HANDSHAKE', 2);
defined('WEBSOCKET_STATUS_FRAME') or define('WEBSOCKET_STATUS_FRAME', 3);
defined('WEBSOCKET_STATUS_ACTIVE') or define('WEBSOCKET_STATUS_ACTIVE', 3);
defined('SWOOLE_FAST_PACK') or define('SWOOLE_FAST_PACK', 1);
defined('UNSERIALIZE_OBJECT_TO_ARRAY') or define('UNSERIALIZE_OBJECT_TO_ARRAY', 1);
defined('UNSERIALIZE_OBJECT_TO_STDCLASS') or define('UNSERIALIZE_OBJECT_TO_STDCLASS', 2);


/**
 * ext functions:
 */

function swoole_version () :NULL {}
function swoole_cpu_num () :NULL {}
function swoole_last_error () :NULL {}
function swoole_event_add ($fd, $read_callback, $write_callback = NULL, $events = NULL) :NULL {}
function swoole_event_set ($fd, $read_callback = NULL, $write_callback = NULL, $events = NULL) :NULL {}
function swoole_event_del ($fd) :NULL {}
function swoole_event_exit () :NULL {}
function swoole_event_wait () :NULL {}
function swoole_event_write ($fd, $data) :NULL {}
function swoole_event_defer ($callback) :NULL {}
function swoole_event_cycle ($callback) :NULL {}
function swoole_timer_after ($ms, $callback, $param = NULL) :NULL {}
function swoole_timer_tick ($ms, $callback) :NULL {}
function swoole_timer_exists ($timer_id) :NULL {}
function swoole_timer_clear ($timer_id) :NULL {}
function swoole_async_set (array $settings) :NULL {}
function swoole_async_read ($filename, $callback, $chunk_size = NULL, $offset = NULL) :NULL {}
function swoole_async_write ($filename, $content, $offset = NULL, $callback = NULL) :NULL {}
function swoole_async_readfile ($filename, $callback) :NULL {}
function swoole_async_writefile ($filename, $content, $callback = NULL, $flags = NULL) :NULL {}
function swoole_async_dns_lookup ($hostname, $callback) :NULL {}
function swoole_async_dns_lookup_coro ($domain_name) :NULL {}
function swoole_client_select (&$read_array, &$write_array, &$error_array, $timeout = NULL) :NULL {}
function swoole_select (&$read_array, &$write_array, &$error_array, $timeout = NULL) :NULL {}
function swoole_set_process_name ($process_name) :NULL {}
function swoole_get_local_ip () :NULL {}
function swoole_get_local_mac () :NULL {}
function swoole_strerror ($errno) :NULL {}
function swoole_errno () :NULL {}


/**
 * ext classes:
 */

namespace Swoole {
    class Lock {
        const FILELOCK = 2;
        const MUTEX = 3;
        const SEM = 4;
        const RWLOCK = 1;
        const SPINLOCK = 5;


        public function __construct ($type = NULL, $filename = NULL) {}
        public function __destruct () {}
        public function lock () :NULL {}
        public function lockwait ($timeout = NULL) :NULL {}
        public function trylock () :NULL {}
        public function lock_read () :NULL {}
        public function trylock_read () :NULL {}
        public function unlock () :NULL {}
    }
}

namespace Swoole {
    class Mmap {


        public static function open ($filename, $size = NULL, $offset = NULL) :NULL {}
    }
}

namespace Swoole {
    class MySQL {
        const STATE_QUERY = 0;
        const STATE_READ_START = 1;
        const STATE_READ_FIELD  = 2;
        const STATE_READ_ROW = 3;
        const STATE_READ_END = 5;
        const STATE_CLOSED = 6;

        public $serverInfo;
        public $sock;
        public $connected;
        public $errno;
        public $connect_errno;
        public $error;
        public $connect_error;
        public $insert_id;
        public $affected_rows;
        public $onConnect;
        public $onClose;

        public function __construct () {}
        public function __destruct () {}
        public function connect (array $server_config, $callback) :NULL {}
        public function begin ($callback) :NULL {}
        public function commit ($callback) :NULL {}
        public function rollback ($callback) :NULL {}
        public function query ($sql, $callback) :NULL {}
        public function close () :NULL {}
        public function getState () :NULL {}
        public function on ($event_name, $callback) :NULL {}
    }
}

namespace Swoole {
    class Timer {


        public static function tick ($ms, $callback, $param = NULL) :NULL {}
        public static function after ($ms, $callback) :NULL {}
        public static function exists ($timer_id) :NULL {}
        public static function clear ($timer_id) :NULL {}
    }
}

namespace Swoole {
    class Event {


        public static function add ($fd, $read_callback, $write_callback = NULL, $events = NULL) :NULL {}
        public static function del ($fd) :NULL {}
        public static function set ($fd, $read_callback = NULL, $write_callback = NULL, $events = NULL) :NULL {}
        public static function exit () :NULL {}
        public static function write ($fd, $data) :NULL {}
        public static function wait () :NULL {}
        public static function defer ($callback) :NULL {}
        public static function cycle ($callback) :NULL {}
    }
}

namespace Swoole {
    class Async {


        public static function read ($filename, $callback, $chunk_size = NULL, $offset = NULL) :NULL {}
        public static function write ($filename, $content, $offset = NULL, $callback = NULL) :NULL {}
        public static function readFile ($filename, $callback) :NULL {}
        public static function writeFile ($filename, $content, $callback = NULL, $flags = NULL) :NULL {}
        public static function dnsLookup ($hostname, $callback) :NULL {}
        public static function dnsLookupCoro ($domain_name) :NULL {}
        public static function set (array $settings) :NULL {}
        public static function exec ($command, $callback) :NULL {}
    }
}

namespace Swoole {
    class Table {
        const TYPE_INT = 1;
        const TYPE_STRING = 7;
        const TYPE_FLOAT = 6;


        public function __construct ($table_size, $conflict_proportion = NULL) {}
        public function column ($name, $type, $size = NULL) :NULL {}
        public function create () :NULL {}
        public function destroy () :NULL {}
        public function set ($key, array $value) :NULL {}
        public function get ($key, $field = NULL) :NULL {}
        public function count () :NULL {}
        public function del ($key) :NULL {}
        public function exist ($key) :NULL {}
        public function incr ($key, $column, $incrby = NULL) :NULL {}
        public function decr ($key, $column, $decrby = NULL) :NULL {}
        public function getMemorySize () :NULL {}
        public function offsetExists ($offset) :NULL {}
        public function offsetGet ($offset) :NULL {}
        public function offsetSet ($offset, $value) :NULL {}
        public function offsetUnset ($offset) :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
        public function rewind () :NULL {}
        public function next () :NULL {}
        public function current () :NULL {}
        public function key () :NULL {}
        public function valid () :NULL {}
    }
}

namespace Swoole {
    class Client {
        const MSG_OOB = 1;
        const MSG_PEEK = 2;
        const MSG_DONTWAIT = 64;
        const MSG_WAITALL = 256;

        public $errCode;
        public $sock;
        public $reuse;
        public $reuseCount;
        public $type;
        public $id;
        public $setting;
        public $onConnect;
        public $onError;
        public $onReceive;
        public $onClose;
        public $onBufferFull;
        public $onBufferEmpty;

        public function __construct ($type, $async = NULL) {}
        public function __destruct () {}
        public function set (array $settings) :NULL {}
        public function connect ($host, $port = NULL, $timeout = NULL, $sock_flag = NULL) :NULL {}
        public function recv ($size = NULL, $flag = NULL) :NULL {}
        public function send ($data, $flag = NULL) :NULL {}
        public function pipe ($dst_socket) :NULL {}
        public function sendfile ($filename, $offset = NULL, $length = NULL) :NULL {}
        public function sendto ($ip, $port, $data) :NULL {}
        public function sleep () :NULL {}
        public function wakeup () :NULL {}
        public function pause () :NULL {}
        public function resume () :NULL {}
        public function isConnected () :NULL {}
        public function getsockname () :NULL {}
        public function getpeername () :NULL {}
        public function close ($force = NULL) :NULL {}
        public function on ($event_name, $callback) :NULL {}
    }
}

namespace Swoole {
    class Buffer {


        public function __construct ($size = NULL) {}
        public function __destruct () {}
        public function __toString () :NULL {}
        public function substr ($offset, $length = NULL, $seek = NULL) :NULL {}
        public function write ($offset, $data) :NULL {}
        public function read ($offset, $length) :NULL {}
        public function append ($data) :NULL {}
        public function expand ($size) :NULL {}
        public function recycle () :NULL {}
        public function clear () :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole {
    class Atomic {


        public function __construct ($value = NULL) {}
        public function add ($add_value = NULL) :NULL {}
        public function sub ($sub_value = NULL) :NULL {}
        public function get () :NULL {}
        public function set ($value) :NULL {}
        public function wait ($timeout = NULL) :NULL {}
        public function wakeup ($count = NULL) :NULL {}
        public function cmpset ($cmp_value, $new_value) :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole {
    class Server {

        public $onConnect;
        public $onReceive;
        public $onClose;
        public $onPacket;
        public $onBufferFull;
        public $onBufferEmpty;
        public $onStart;
        public $onShutdown;
        public $onWorkerStart;
        public $onWorkerStop;
        public $onWorkerExit;
        public $onWorkerError;
        public $onTask;
        public $onFinish;
        public $onManagerStart;
        public $onManagerStop;
        public $onPipeMessage;
        public $setting;
        public $connections;
        public $host;
        public $port;
        public $type;
        public $mode;
        public $ports;
        public $master_pid;
        public $manager_pid;
        public $worker_id;
        public $taskworker;
        public $worker_pid;

        public function __construct ($host, $port = NULL, $mode = NULL, $sock_type = NULL) {}
        public function __destruct () {}
        public function listen ($host, $port, $sock_type) :NULL {}
        public function addlistener ($host, $port, $sock_type) :NULL {}
        public function on ($event_name, $callback) :NULL {}
        public function set (array $settings) :NULL {}
        public function start () :NULL {}
        public function send ($fd, $send_data, $reactor_id = NULL) :NULL {}
        public function sendto ($ip, $port, $send_data, $server_socket = NULL) :NULL {}
        public function sendwait ($conn_fd, $send_data) :NULL {}
        public function exist ($fd) :NULL {}
        public function protect ($fd, $is_protected = NULL) :NULL {}
        public function sendfile ($conn_fd, $filename, $offset = NULL, $length = NULL) :NULL {}
        public function close ($fd, $reset = NULL) :NULL {}
        public function confirm ($fd) :NULL {}
        public function pause ($fd) :NULL {}
        public function resume ($fd) :NULL {}
        public function task ($data, $worker_id = NULL, $finish_callback = NULL) :NULL {}
        public function taskwait ($data, $timeout = NULL, $worker_id = NULL) :NULL {}
        public function taskWaitMulti (array $tasks, $timeout = NULL) :NULL {}
        public function taskCo (array $tasks, $timeout = NULL) :NULL {}
        public function finish ($data) :NULL {}
        public function reload () :NULL {}
        public function shutdown () :NULL {}
        public function stop ($worker_id = NULL) :NULL {}
        public function getLastError () :NULL {}
        public function heartbeat ($reactor_id) :NULL {}
        public function connection_info ($fd, $reactor_id = NULL) :NULL {}
        public function connection_list ($start_fd, $find_count = NULL) :NULL {}
        public function getClientInfo ($fd, $reactor_id = NULL) :NULL {}
        public function getClientList ($start_fd, $find_count = NULL) :NULL {}
        public function after ($ms, $callback, $param = NULL) :NULL {}
        public function tick ($ms, $callback) :NULL {}
        public function clearTimer ($timer_id) :NULL {}
        public function defer ($callback) :NULL {}
        public function sendMessage ($dst_worker_id, $data) :NULL {}
        public function addProcess (\swoole_process $process) :NULL {}
        public function stats () :NULL {}
        public function bind ($fd, $uid) :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole {
    class Channel {


        public function __construct ($size) {}
        public function __destruct () {}
        public function push ($data) :NULL {}
        public function pop () :NULL {}
        public function stats () :NULL {}
    }
}

namespace Swoole {
    class Process {
        const IPC_NOWAIT = 256;

        public $pipe;
        public $callback;
        public $msgQueueId;
        public $msgQueueKey;
        public $pid;
        public $id;

        public function __construct ($callback, $redirect_stdin_and_stdout = NULL, $pipe_type = NULL) {}
        public function __destruct () {}
        public static function wait ($blocking = NULL) :NULL {}
        public static function signal ($signal_no, $callback) :NULL {}
        public static function alarm ($usec) :NULL {}
        public static function kill ($pid, $signal_no = NULL) :NULL {}
        public static function daemon ($nochdir = NULL, $noclose = NULL) :NULL {}
        public function setTimeout ($seconds) :NULL {}
        public function useQueue ($key = NULL, $mode = NULL) :NULL {}
        public function statQueue () :NULL {}
        public function freeQueue () :NULL {}
        public function start () :NULL {}
        public function write ($data) :NULL {}
        public function close () :NULL {}
        public function read ($size = NULL) :NULL {}
        public function push ($data) :NULL {}
        public function pop ($size = NULL) :NULL {}
        public function exit ($exit_code = NULL) :NULL {}
        public function exec ($exec_file, $args) :NULL {}
        public function name ($process_name) :NULL {}
    }
}

namespace Swoole {
    class Coroutine {


        public static function create ($func) :NULL {}
        public static function cli_wait () :NULL {}
        public static function suspend ($uid) :NULL {}
        public static function resume ($uid) :NULL {}
        public static function getuid () :NULL {}
        public static function sleep ($seconds) :NULL {}
        public static function fread ($handle, $length = NULL) :NULL {}
        public static function fwrite ($handle, $string, $length = NULL) :NULL {}
        public static function gethostbyname ($domain_name, $family = NULL) :NULL {}
        public static function call_user_func ($func) :NULL {}
        public static function call_user_func_array ($func, array $params) :NULL {}
    }
}

namespace Swoole {
    class Exception extends \Exception {

        protected $message;
        protected $code;
        protected $file;
        protected $line;

        public function __construct ($message = NULL, $code = NULL, $previous = NULL) {}
        public function __wakeup () :NULL {}
        public function __toString () :NULL {}
    }
}

namespace Swoole\Table {
    class Row {

        public $key;
        public $value;

        public function offsetExists ($offset) :NULL {}
        public function offsetGet ($offset) :NULL {}
        public function offsetSet ($offset, $value) :NULL {}
        public function offsetUnset ($offset) :NULL {}
        public function __destruct () {}
    }
}

namespace Swoole {
    class Serialize {


        public static function pack ($data, $flag = NULL) :NULL {}
        public static function unpack ($string, $args = NULL) :NULL {}
    }
}

namespace Swoole\Http {
    class Client {

        public $type;
        public $errCode;
        public $sock;
        public $statusCode;
        public $host;
        public $port;
        public $requestMethod;
        public $requestHeaders;
        public $requestBody;
        public $uploadFiles;
        public $set_cookie_headers;
        public $downloadFile;
        public $headers;
        public $cookies;
        public $body;
        public $onConnect;
        public $onError;
        public $onMessage;
        public $onClose;

        public function __construct ($host, $port = NULL, $ssl = NULL) {}
        public function __destruct () {}
        public function set (array $settings) :NULL {}
        public function setMethod ($method) :NULL {}
        public function setHeaders (array $headers) :NULL {}
        public function setCookies (array $cookies) :NULL {}
        public function setData ($data) :NULL {}
        public function addFile ($path, $name, $type = NULL, $filename = NULL, $offset = NULL, $length = NULL) :NULL {}
        public function execute ($path, $callback) :NULL {}
        public function push ($data, $opcode = NULL, $finish = NULL) :NULL {}
        public function get ($path, $callback) :NULL {}
        public function post ($path, $data, $callback) :NULL {}
        public function upgrade ($path, $callback) :NULL {}
        public function download ($path, $file, $callback, $offset = NULL) :NULL {}
        public function isConnected () :NULL {}
        public function close () :NULL {}
        public function on ($event_name, $callback) :NULL {}
    }
}

namespace Swoole\Http {
    class Server extends \Swoole\Server {

        public $onConnect;
        public $onReceive;
        public $onClose;
        public $onPacket;
        public $onBufferFull;
        public $onBufferEmpty;
        public $onStart;
        public $onShutdown;
        public $onWorkerStart;
        public $onWorkerStop;
        public $onWorkerExit;
        public $onWorkerError;
        public $onTask;
        public $onFinish;
        public $onManagerStart;
        public $onManagerStop;
        public $onPipeMessage;
        public $connections;
        public $host;
        public $port;
        public $type;
        public $mode;
        public $ports;
        public $master_pid;
        public $manager_pid;
        public $worker_id;
        public $taskworker;
        public $worker_pid;
        public $onRequest;
        public $onHandshake;
        public $setting;

        public function on ($event_name, $callback) :NULL {}
        public function start () :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
        public function __construct ($host, $port = NULL, $mode = NULL, $sock_type = NULL) {}
        public function __destruct () {}
        public function listen ($host, $port, $sock_type) :NULL {}
        public function addlistener ($host, $port, $sock_type) :NULL {}
        public function set (array $settings) :NULL {}
        public function send ($fd, $send_data, $reactor_id = NULL) :NULL {}
        public function sendto ($ip, $port, $send_data, $server_socket = NULL) :NULL {}
        public function sendwait ($conn_fd, $send_data) :NULL {}
        public function exist ($fd) :NULL {}
        public function protect ($fd, $is_protected = NULL) :NULL {}
        public function sendfile ($conn_fd, $filename, $offset = NULL, $length = NULL) :NULL {}
        public function close ($fd, $reset = NULL) :NULL {}
        public function confirm ($fd) :NULL {}
        public function pause ($fd) :NULL {}
        public function resume ($fd) :NULL {}
        public function task ($data, $worker_id = NULL, $finish_callback = NULL) :NULL {}
        public function taskwait ($data, $timeout = NULL, $worker_id = NULL) :NULL {}
        public function taskWaitMulti (array $tasks, $timeout = NULL) :NULL {}
        public function taskCo (array $tasks, $timeout = NULL) :NULL {}
        public function finish ($data) :NULL {}
        public function reload () :NULL {}
        public function shutdown () :NULL {}
        public function stop ($worker_id = NULL) :NULL {}
        public function getLastError () :NULL {}
        public function heartbeat ($reactor_id) :NULL {}
        public function connection_info ($fd, $reactor_id = NULL) :NULL {}
        public function connection_list ($start_fd, $find_count = NULL) :NULL {}
        public function getClientInfo ($fd, $reactor_id = NULL) :NULL {}
        public function getClientList ($start_fd, $find_count = NULL) :NULL {}
        public function after ($ms, $callback, $param = NULL) :NULL {}
        public function tick ($ms, $callback) :NULL {}
        public function clearTimer ($timer_id) :NULL {}
        public function defer ($callback) :NULL {}
        public function sendMessage ($dst_worker_id, $data) :NULL {}
        public function addProcess (\swoole_process $process) :NULL {}
        public function stats () :NULL {}
        public function bind ($fd, $uid) :NULL {}
    }
}

namespace Swoole\Server {
    class Port {

        public $onConnect;
        public $onReceive;
        public $onClose;
        public $onPacket;
        public $onBufferFull;
        public $onBufferEmpty;
        public $onRequest;
        public $onHandShake;
        public $onMessage;
        public $onOpen;
        public $host;
        public $port;
        public $type;
        public $sock;
        public $setting;
        public $connections;

        private function __construct () {}
        public function __destruct () {}
        public function set (array $settings) :NULL {}
        public function on ($event_name, $callback) :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole\Atomic {
    class Long {


        public function __construct ($value = NULL) {}
        public function add ($add_value = NULL) :NULL {}
        public function sub ($sub_value = NULL) :NULL {}
        public function get () :NULL {}
        public function set ($value) :NULL {}
        public function cmpset ($cmp_value, $new_value) :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole\Http {
    class Request {

        public $fd;
        public $header;
        public $server;
        public $request;
        public $cookie;
        public $get;
        public $files;
        public $post;
        public $tmpfiles;

        public function rawcontent () :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
        public function __destruct () {}
    }
}

namespace Swoole\Redis {
    class Server extends \Swoole\Server {
        const NIL = 1;
        const ERROR = 0;
        const STATUS = 2;
        const INT = 3;
        const STRING = 4;
        const SET = 5;
        const MAP = 6;

        public $onConnect;
        public $onReceive;
        public $onClose;
        public $onPacket;
        public $onBufferFull;
        public $onBufferEmpty;
        public $onStart;
        public $onShutdown;
        public $onWorkerStart;
        public $onWorkerStop;
        public $onWorkerExit;
        public $onWorkerError;
        public $onTask;
        public $onFinish;
        public $onManagerStart;
        public $onManagerStop;
        public $onPipeMessage;
        public $setting;
        public $connections;
        public $host;
        public $port;
        public $type;
        public $mode;
        public $ports;
        public $master_pid;
        public $manager_pid;
        public $worker_id;
        public $taskworker;
        public $worker_pid;

        public function start () :NULL {}
        public function setHandler ($command, $callback, $number_of_string_param = NULL, $type_of_array_param = NULL) :NULL {}
        public static function format ($type, $value = NULL) :NULL {}
        public function __construct ($host, $port = NULL, $mode = NULL, $sock_type = NULL) {}
        public function __destruct () {}
        public function listen ($host, $port, $sock_type) :NULL {}
        public function addlistener ($host, $port, $sock_type) :NULL {}
        public function on ($event_name, $callback) :NULL {}
        public function set (array $settings) :NULL {}
        public function send ($fd, $send_data, $reactor_id = NULL) :NULL {}
        public function sendto ($ip, $port, $send_data, $server_socket = NULL) :NULL {}
        public function sendwait ($conn_fd, $send_data) :NULL {}
        public function exist ($fd) :NULL {}
        public function protect ($fd, $is_protected = NULL) :NULL {}
        public function sendfile ($conn_fd, $filename, $offset = NULL, $length = NULL) :NULL {}
        public function close ($fd, $reset = NULL) :NULL {}
        public function confirm ($fd) :NULL {}
        public function pause ($fd) :NULL {}
        public function resume ($fd) :NULL {}
        public function task ($data, $worker_id = NULL, $finish_callback = NULL) :NULL {}
        public function taskwait ($data, $timeout = NULL, $worker_id = NULL) :NULL {}
        public function taskWaitMulti (array $tasks, $timeout = NULL) :NULL {}
        public function taskCo (array $tasks, $timeout = NULL) :NULL {}
        public function finish ($data) :NULL {}
        public function reload () :NULL {}
        public function shutdown () :NULL {}
        public function stop ($worker_id = NULL) :NULL {}
        public function getLastError () :NULL {}
        public function heartbeat ($reactor_id) :NULL {}
        public function connection_info ($fd, $reactor_id = NULL) :NULL {}
        public function connection_list ($start_fd, $find_count = NULL) :NULL {}
        public function getClientInfo ($fd, $reactor_id = NULL) :NULL {}
        public function getClientList ($start_fd, $find_count = NULL) :NULL {}
        public function after ($ms, $callback, $param = NULL) :NULL {}
        public function tick ($ms, $callback) :NULL {}
        public function clearTimer ($timer_id) :NULL {}
        public function defer ($callback) :NULL {}
        public function sendMessage ($dst_worker_id, $data) :NULL {}
        public function addProcess (\swoole_process $process) :NULL {}
        public function stats () :NULL {}
        public function bind ($fd, $uid) :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole\Http {
    class Response {

        public $fd;
        public $header;
        public $cookie;
        public $trailer;

        public function initHeader () :NULL {}
        public function cookie ($name, $value = NULL, $expires = NULL, $path = NULL, $domain = NULL, $secure = NULL, $httponly = NULL) :NULL {}
        public function rawcookie ($name, $value = NULL, $expires = NULL, $path = NULL, $domain = NULL, $secure = NULL, $httponly = NULL) :NULL {}
        public function status ($http_code) :NULL {}
        public function header ($key, $value, $ucwords = NULL) :NULL {}
        public function write ($content) :NULL {}
        public function end ($content = NULL) :NULL {}
        public function sendfile ($filename, $offset = NULL, $length = NULL) :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
        public function __destruct () {}
    }
}

namespace Swoole\Coroutine {
    class MySQL {

        private $serverInfo;
        public $sock;
        public $connected;
        public $connect_error;
        public $connect_errno;
        public $affected_rows;
        public $insert_id;
        public $error;
        public $errno;

        public function __construct () {}
        public function __destruct () {}
        public function connect (array $server_config) :NULL {}
        public function query ($sql, $timeout = NULL) :NULL {}
        public function recv () :NULL {}
        public function begin () :NULL {}
        public function commit () :NULL {}
        public function rollback () :NULL {}
        public function prepare ($query) :NULL {}
        public function execute ($query) :NULL {}
        public function setDefer ($defer = NULL) :NULL {}
        public function getDefer () :NULL {}
        public function close () :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole\MySQL {
    class Exception extends \Exception {

        protected $message;
        protected $code;
        protected $file;
        protected $line;

        public function __construct ($message = NULL, $code = NULL, $previous = NULL) {}
        public function __wakeup () :NULL {}
        public function __toString () :NULL {}
    }
}

namespace Swoole\WebSocket {
    class Frame {


    }
}

namespace Swoole\Coroutine {
    class Client {
        const MSG_OOB = 1;
        const MSG_PEEK = 2;
        const MSG_DONTWAIT = 64;
        const MSG_WAITALL = 256;

        public $errCode;
        public $sock;
        public $type;
        public $setting;

        public function __construct ($type) {}
        public function __destruct () {}
        public function set (array $settings) :NULL {}
        public function connect ($host, $port = NULL, $timeout = NULL) :NULL {}
        public function recv () :NULL {}
        public function send ($data, $flag = NULL) :NULL {}
        public function sendfile ($filename, $offset = NULL, $length = NULL) :NULL {}
        public function sendto ($ip, $port, $data) :NULL {}
        public function isConnected () :NULL {}
        public function getsockname () :NULL {}
        public function getpeername () :NULL {}
        public function close () :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole\WebSocket {
    class Server extends \Swoole\Http\Server {

        public $onConnect;
        public $onReceive;
        public $onClose;
        public $onPacket;
        public $onBufferFull;
        public $onBufferEmpty;
        public $onStart;
        public $onShutdown;
        public $onWorkerStart;
        public $onWorkerStop;
        public $onWorkerExit;
        public $onWorkerError;
        public $onTask;
        public $onFinish;
        public $onManagerStart;
        public $onManagerStop;
        public $onPipeMessage;
        public $connections;
        public $host;
        public $port;
        public $type;
        public $mode;
        public $ports;
        public $master_pid;
        public $manager_pid;
        public $worker_id;
        public $taskworker;
        public $worker_pid;
        public $onRequest;
        public $onHandshake;
        public $setting;

        public function on ($event_name, $callback) :NULL {}
        public function push ($fd, $data, $opcode = NULL, $finish = NULL) :NULL {}
        public function exist ($fd) :NULL {}
        public static function pack ($data, $opcode = NULL, $finish = NULL, $mask = NULL) :NULL {}
        public static function unpack ($data) :NULL {}
        public function start () :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
        public function __construct ($host, $port = NULL, $mode = NULL, $sock_type = NULL) {}
        public function __destruct () {}
        public function listen ($host, $port, $sock_type) :NULL {}
        public function addlistener ($host, $port, $sock_type) :NULL {}
        public function set (array $settings) :NULL {}
        public function send ($fd, $send_data, $reactor_id = NULL) :NULL {}
        public function sendto ($ip, $port, $send_data, $server_socket = NULL) :NULL {}
        public function sendwait ($conn_fd, $send_data) :NULL {}
        public function protect ($fd, $is_protected = NULL) :NULL {}
        public function sendfile ($conn_fd, $filename, $offset = NULL, $length = NULL) :NULL {}
        public function close ($fd, $reset = NULL) :NULL {}
        public function confirm ($fd) :NULL {}
        public function pause ($fd) :NULL {}
        public function resume ($fd) :NULL {}
        public function task ($data, $worker_id = NULL, $finish_callback = NULL) :NULL {}
        public function taskwait ($data, $timeout = NULL, $worker_id = NULL) :NULL {}
        public function taskWaitMulti (array $tasks, $timeout = NULL) :NULL {}
        public function taskCo (array $tasks, $timeout = NULL) :NULL {}
        public function finish ($data) :NULL {}
        public function reload () :NULL {}
        public function shutdown () :NULL {}
        public function stop ($worker_id = NULL) :NULL {}
        public function getLastError () :NULL {}
        public function heartbeat ($reactor_id) :NULL {}
        public function connection_info ($fd, $reactor_id = NULL) :NULL {}
        public function connection_list ($start_fd, $find_count = NULL) :NULL {}
        public function getClientInfo ($fd, $reactor_id = NULL) :NULL {}
        public function getClientList ($start_fd, $find_count = NULL) :NULL {}
        public function after ($ms, $callback, $param = NULL) :NULL {}
        public function tick ($ms, $callback) :NULL {}
        public function clearTimer ($timer_id) :NULL {}
        public function defer ($callback) :NULL {}
        public function sendMessage ($dst_worker_id, $data) :NULL {}
        public function addProcess (\swoole_process $process) :NULL {}
        public function stats () :NULL {}
        public function bind ($fd, $uid) :NULL {}
    }
}

namespace Swoole\Connection {
    class Iterator {


        public function rewind () :NULL {}
        public function next () :NULL {}
        public function current () :NULL {}
        public function key () :NULL {}
        public function valid () :NULL {}
        public function count () :NULL {}
        public function offsetExists ($fd) :NULL {}
        public function offsetGet ($fd) :NULL {}
        public function offsetSet ($fd, $value) :NULL {}
        public function offsetUnset ($fd) :NULL {}
    }
}

namespace Swoole\Coroutine\Http {
    class Client {

        public $type;
        public $errCode;
        public $statusCode;
        public $host;
        public $port;
        public $requestMethod;
        public $requestHeaders;
        public $requestBody;
        public $uploadFiles;
        public $headers;
        public $cookies;
        public $body;

        public function __construct () {}
        public function __destruct () {}
        public function set () :NULL {}
        public function setMethod () :NULL {}
        public function setHeaders () :NULL {}
        public function setCookies () :NULL {}
        public function setData () :NULL {}
        public function execute () :NULL {}
        public function get () :NULL {}
        public function post () :NULL {}
        public function addFile () :NULL {}
        public function isConnected () :NULL {}
        public function close () :NULL {}
        public function setDefer () :NULL {}
        public function getDefer () :NULL {}
        public function recv () :NULL {}
        public function __sleep () :NULL {}
        public function __wakeup () :NULL {}
    }
}

namespace Swoole\Coroutine\MySQL {
    class Exception extends \Exception {

        protected $message;
        protected $code;
        protected $file;
        protected $line;

        public function __construct ($message = NULL, $code = NULL, $previous = NULL) {}
        public function __wakeup () :NULL {}
        public function __toString () :NULL {}
    }
}

namespace { class swoole_mmap extends Swoole\Mmap {}}
namespace { class swoole_lock extends Swoole\Lock {}}
namespace { class swoole_mysql extends Swoole\MySQL {}}
namespace { class swoole_timer extends Swoole\Timer {}}
namespace { class swoole_event extends Swoole\Event {}}
namespace { class swoole_table extends Swoole\Table {}}
namespace { class swoole_async extends Swoole\Async {}}
namespace { class swoole_atomic extends Swoole\Atomic {}}
namespace { class swoole_server extends Swoole\Server {}}
namespace { class swoole_client extends Swoole\Client {}}
namespace { class swoole_buffer extends Swoole\Buffer {}}
namespace { class swoole_process extends Swoole\Process {}}
namespace { class swoole_channel extends Swoole\Channel {}}
namespace { class swoole_coroutine extends Swoole\Coroutine {}}
namespace { class swoole_serialize extends Swoole\Serialize {}}
namespace { class swoole_exception extends Swoole\Exception {}}
namespace { class swoole_table_row extends Swoole\Table\Row {}}
namespace { class swoole_atomic_long extends Swoole\Atomic\Long {}}
namespace { class swoole_http_server extends Swoole\Http\Server {}}
namespace { class swoole_http_client extends Swoole\Http\Client {}}
namespace { class swoole_client_coro extends Swoole\Coroutine\Client {}}
namespace { class swoole_server_port extends Swoole\Server\Port {}}
namespace { class swoole_http_request extends Swoole\Http\Request {}}
namespace { class swoole_redis_server extends Swoole\Redis\Server {}}
namespace { class swoole_http_response extends Swoole\Http\Response {}}
namespace { class swoole_websocket_frame extends Swoole\WebSocket\Frame {}}
namespace { class swoole_mysql_exception extends Swoole\MySQL\Exception {}}
namespace { class swoole_websocket_server extends Swoole\WebSocket\Server {}}
namespace { class swoole_connection_iterator extends Swoole\Connection\Iterator {}}
namespace { class swoole_http_client_coro extends Swoole\Coroutine\Http\Client {}}


