<?php

/**
 * this file is generated by https://github.com/nisnaker/ide-helper-generator
 *
 *
 * ext info:
 *
 * tideways
 * 
 * tideways => 4.1.4
 * Connection (tideways.connection) => unix:///var/run/tideways/tidewaysd.sock
 * UDP Connection (tideways.udp_connection) => 127.0.0.1:8135
 * Default API Key (tideways.api_key) =>  
 * Default Sample-Rate (tideways.sample_rate) => 20
 * Framework Detection (tideways.framework) =>  
 * Service Name (tideways.service) =>  
 * Automatically Start (tideways.auto_start) => Yes
 * Tideways Collect Mode (tideways.collect) => tracing
 * Tideways Monitoring Mode (tideways.monitor) => basic
 * CLI Monitoring enabled (tideways.monitor_cli) => 0
 * Timeout for talk to Daemon (tideways.timeout) => 10000
 * Allowed Distributed Tracing Hosts (tideways.distributed_tracing_hosts) => 127.0.0.1
 * Load PHP Library (tideways.auto_prepend_library) => Yes
 * Tideways.php found => Yes
 * 
 */


/**
 * ext constants:
 */

defined('TIDEWAYS_FLAGS_CPU') or define('TIDEWAYS_FLAGS_CPU', 2);
defined('TIDEWAYS_FLAGS_MEMORY') or define('TIDEWAYS_FLAGS_MEMORY', 4);
defined('TIDEWAYS_FLAGS_NO_BUILTINS') or define('TIDEWAYS_FLAGS_NO_BUILTINS', 1);
defined('TIDEWAYS_FLAGS_NO_USERLAND') or define('TIDEWAYS_FLAGS_NO_USERLAND', 8);
defined('TIDEWAYS_FLAGS_NO_COMPILE') or define('TIDEWAYS_FLAGS_NO_COMPILE', 16);
defined('TIDEWAYS_FLAGS_NO_SPANS') or define('TIDEWAYS_FLAGS_NO_SPANS', 32);
defined('TIDEWAYS_FLAGS_NO_HIERACHICAL') or define('TIDEWAYS_FLAGS_NO_HIERACHICAL', 64);


/**
 * ext functions:
 */

function tideways_enable ($flags = NULL, $options = NULL) {}
function tideways_disable () {}
function tideways_transaction_name () {}
function tideways_prepend_overwritten () {}
function tideways_fatal_backtrace () {}
function tideways_last_detected_exception () {}
function tideways_last_fatal_error () {}
function tideways_sql_minify ($sql = NULL) {}
function tideways_span_create ($category = NULL) {}
function tideways_get_spans () {}
function tideways_span_timer_start ($span = NULL) {}
function tideways_span_timer_stop ($span = NULL) {}
function tideways_span_annotate ($span = NULL, $annotations = NULL) {}
function tideways_span_watch ($name = NULL, $category = NULL) {}
function tideways_span_callback ($name = NULL, $callback = NULL) {}


/**
 * ext classes:
 */



